spring.application.name=clinic_db


spring.datasource.url=jdbc:postgresql://localhost:5432/clinic_db
spring.datasource.username=postgres
spring.datasource.password=Prince1970.

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true